---
- hosts: all
  become: false
  gather_facts: false

  tasks:

  - name: Configure screenrc
    shell: 
      cmd: "echo 'defscrollback 20000' >> ~/.screenrc"
    register: comnd

  - name: Display output.
    debug:
      msg: "{{ comnd.stdout_lines }}"
