---
- hosts: all
  become: false
  gather_facts: false

  tasks:

  - name: Check disk usage and grep for 
    ansible.builtin.shell: df -h | grep -e boot -e root
    register: process_status
    failed_when: process_status.rc != 0

  - name: Display process status
    ansible.builtin.debug:
     var: process_status.stdout_lines
